# basic workflow to help you get started with Actions

#给工作流起名字
name: CI to Docker Hub

#定义一些事件
on:
  #当主分支push时候触发
  push:
    branches: [ master ]



#工作流有多个job组成，可以队列执行或者并行
jobs:
  build:
    runs-on: ubuntu-latest

    #step时job的一部分（本质是一个任务队列）
    steps:

      #git拉取代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      #登录dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_DOCKERID }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      #设置docker 构建器
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      #构建和发布
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: jwzg/ea-image:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
